/**
 * Raptor Reporting service
 * A simple reporting service that enable users to design and generate web-based reports.
 * Built on top of the JasperReports - an open source reporting library
 * 2016 © ATT Service Assurance  - Raptor POC team
 *
 */
package com.att.raptor.report.data.domain;

import com.att.raptor.report.data.support.CustomDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.joda.time.DateTime;
import org.springframework.data.annotation.Version;
import org.springframework.data.domain.Auditable;

/**
 * @author ebrimatunkara DomainAudit class that will provide the auditing for
 * domain objects
 */
public abstract class Audit implements Auditable<String, String> {
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @Version
    private Long version;

    private String createdBy;
    private String lastModifiedBy;
    
    @JsonSerialize(using = CustomDateSerializer.class)
    private DateTime createdDate;
    
    @JsonSerialize(using = CustomDateSerializer.class)
    private DateTime lastModifiedDate;

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Persistable#isNew()
     */
    @Override
    public boolean isNew() {
        /**
         * Assuming the Id is generated by database. If not, then need to
         * override in each model depending on how to identify if a Model is a
         * new one or already saved Model.  
		 *
         */
        return getId() == null;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#getCreatedBy()
     */
    @Override
    public String getCreatedBy() {
        // TODO Auto-generated method stub
        return createdBy;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#setCreatedBy(java.lang.Object)
     */
    @Override
    public void setCreatedBy(String createdBy) {
        // TODO Auto-generated method stub
        this.createdBy = createdBy;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#getCreatedDate()
     */
    @Override
    public DateTime getCreatedDate() {
        // TODO Auto-generated method stub
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#setCreatedDate(org.joda.time.DateTime)
     */
    @Override
    public void setCreatedDate(DateTime creationDate) {
        // TODO Auto-generated method stub
        this.createdDate = creationDate;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#getLastModifiedBy()
     */
    @Override
    public String getLastModifiedBy() {
        // TODO Auto-generated method stub
        return lastModifiedBy;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#setLastModifiedBy(java.lang.Object)
     */
    @Override
    public void setLastModifiedBy(String lastModifiedBy) {
        // TODO Auto-generated method stub
        this.lastModifiedBy = lastModifiedBy;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#getLastModifiedDate()
     */
    @Override
    public DateTime getLastModifiedDate() {
        // TODO Auto-generated method stub
        return lastModifiedDate;
    }

    /* (non-Javadoc)
	 * @see org.springframework.data.domain.Auditable#setLastModifiedDate(org.joda.time.DateTime)
     */
    @Override
    public void setLastModifiedDate(DateTime lastModifiedDate) {
        // TODO Auto-generated method stub
        this.lastModifiedDate = lastModifiedDate;
    }

}
